package com.nathalieborodina.theatreapp.data.model;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.nathalieborodina.theatreapp.data.model.PerfomanceEvent;
import com.nathalieborodina.theatreapp.data.model.Ticket;

import com.nathalieborodina.theatreapp.data.model.PerfomanceEventDao;
import com.nathalieborodina.theatreapp.data.model.TicketDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig perfomanceEventDaoConfig;
    private final DaoConfig ticketDaoConfig;

    private final PerfomanceEventDao perfomanceEventDao;
    private final TicketDao ticketDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        perfomanceEventDaoConfig = daoConfigMap.get(PerfomanceEventDao.class).clone();
        perfomanceEventDaoConfig.initIdentityScope(type);

        ticketDaoConfig = daoConfigMap.get(TicketDao.class).clone();
        ticketDaoConfig.initIdentityScope(type);

        perfomanceEventDao = new PerfomanceEventDao(perfomanceEventDaoConfig, this);
        ticketDao = new TicketDao(ticketDaoConfig, this);

        registerDao(PerfomanceEvent.class, perfomanceEventDao);
        registerDao(Ticket.class, ticketDao);
    }
    
    public void clear() {
        perfomanceEventDaoConfig.getIdentityScope().clear();
        ticketDaoConfig.getIdentityScope().clear();
    }

    public PerfomanceEventDao getPerfomanceEventDao() {
        return perfomanceEventDao;
    }

    public TicketDao getTicketDao() {
        return ticketDao;
    }

}
